create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  name text not null,
  phone text not null,
  city text,
  building text,
  elevators text,
  urgency text,
  services text[],
  notes text
);

alter table public.leads enable row level security;

drop policy if exists "Allow anonymous lead inserts" on public.leads;
create policy "Allow anonymous lead inserts"
on public.leads for insert
to anon
with check (true);

-- For dashboard reads in production, prefer Supabase Auth and a private admin panel.
